import { Movie } from './movie';

export const MOVIES: Movie[] = [
  { id: 1,
    title: "Tenet",
    genre: "Thriller / Action / Sci-Fi",
    director: 'Christopher Nolan',
    avgRate: 7.8,
    country: "Canada / USA / UK",
    description: 'Blablabla' },

{ id: 2,
    title: "Dunkirk",
    genre: "Action / Drama / History",
    director: 'Christopher Nolan',
    avgRate: 7.9,
    country: "Canada / USA / UK",
    description: 'Blablabla' },

  { id: 3,
    title: "Interstellar",
    genre: " Adventure / Drama / Sci-Fi",
    director: 'Christopher Nolan',
    avgRate: 8.6,
    country: "Canada / USA / UK",
    description: 'Blablabla' },

   { id: 4,
    title: "The Dark Knight Rises",
    genre: " Adventure / Action",
    director: 'Christopher Nolan',
    avgRate: 8.4,
    country: "Canada / USA / UK",
    description: 'Blablabla' },

  { id: 5,
    title: "Inception",
    genre: " Adventure / Action / Drama",
    director: 'Christopher Nolan',
    avgRate: 8.8,
    country: "Canada / USA / UK",
    description: 'Blablabla' },

  { id: 6,
    title: "The Dark Knight",
    genre: " Action / Drama / Crime",
    director: 'Christopher Nolan',
    avgRate: 9.0,
    country: "Canada / USA / UK",
    description: 'Blablabla' },

  { id: 7,
    title: "The Prestige",
    genre: " Drama / Mystery / Sci-Fi",
    director: 'Christopher Nolan',
    avgRate: 8.5,
    country: "Canada / USA / UK",
    description: 'Blablabla' },

  { id: 8,
    title: "Batman Begins",
    genre: " Action / Adventure",
    director: 'Christopher Nolan',
    avgRate: 8.2,
    country: "Canada / USA / UK",
    description: 'Blablabla' },

];